### ISSUE TITLE
fix manually created JSON structure

### ISSUE THREAD

**Issue by spaceone** [CodeSpoof/uniPass#2]
https://github.com/CodeSpoof/uniPass/blob/master/app/src/main/java/io/codespoof/univpassm/PasswordTask.java#L86
> return createConnection("/univention/auth", "{\"options\":{\"username\":\"" + username + "\",\"password\":\"" + password + "\"}}", null);

and

https://github.com/CodeSpoof/uniPass/blob/master/app/src/main/java/io/codespoof/univpassm/PasswordTask.java#L90
>  return createConnection("/univention/set/password", "{\"options\":{\"password\":{\"password\":\"" + oldPassword + "\",\"new_password\":\"" + newPassword + "\"}}}", cookies) != null;

construct a JSON string manually.
Therefore entering a password like `", "username": "something` will cause a JSON object like:
`"{"options":{"username":"","password":"", "username": "something"}}"`

→ JSON should be constructed with an appropriate JSON library

**Comment by CodeSpoof** [comment]
Thank you, I'm on it
